version: "3.9"
services:
  my-jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    
  
    ports:
      - "8887:8080"
      - "8886:8443"

    volumes:
      - ./logs/:/usr/local/tomcat/logs

    container_name: testjenkinsnewwar012